### PR TITLE
Delete photolist.json

### PR DESCRIPTION
**Pull request by andreweick**
@regisphilibert  -- This pull request deletes data/photolist.json, so I'll send it as a PR so you can merge when at a good point in your development

I've got the URL parameters works to query the list of photos rather than getting the file out of the data folder.  The JSON has changed a smidge (and I can change it again if would be easier to parse)

URL:
To start at the beginning (QueryParam NextToken=0)
https://m2gfewcae1.execute-api.us-east-1.amazonaws.com/Prod/photoapi/?NextToken=0

This will return a JSON with 2 elements -- an array of Name (just as before) and a NextToken.

This pages the results -- to get the next page, pass in the NextToken to the next call and it will start NextToken+1

At the end of the list, NextToken is empty:

curl https://m2gfewcae1.execute-api.us-east-1.amazonaws.com/Prod/photoapi/\?NextToken\=3front-f.jpg

gives

{"Name":["solemn_high_mass_catherdral_palme_de_majorica.jpg"],"NextToken":""}%

### CODE REVIEW

**Comment by andreweick** [comment]
@regisphilibert GoHabs

**Comment by regisphilibert** [comment]
Thanks @andreweick I don't think I will use the PR, the data file is not really used anyhow. I'll just delete it from production.

**Comment by andreweick** [comment]
#GoHabs

**Comment by andreweick** [comment]
(I was just so excited to get my "next token" working!)

**Pull request closed without merging**
