### PR TITLE
Add new theme

### PR DESCRIPTION
**Pull request by regisphilibert**
@andreweick this is for you to check out the theme @budparr created for the site some months ago. You should not merge that branch yet, even if satisfied, as we'll still have some "back end" work to do before final delivery.

Let us know if everything looks good.

### CODE REVIEW

**Comment by andreweick** [comment]
@regisphilibert rather than merging the code files straight into the site, could we make the 'bud-theme' be it's own repo / stand alone theme that is integrated (as any other theme) is integrated?  I think that's cleaner?

**Comment by regisphilibert** [comment]
Hi @andreweick this theme has been created a while back as you know. In a project where themes are open source and maintained by tiers, it makes sense to simply pull the repo as a git submodule or a Hugo Module, but here, this theme has been custom made for your site.

Today I would start by using your project's own layout files rather than putting everything in theme dir, but back then it made more sense. 

If you want we can move the theme files at the root of the project, but I wouldn't recommend hosting the theme on a different repo, as maintaining the site will mean juggling between the two repos and making the necessary submodule upgrades when needed (which will be often when maintaining front end).

**Comment by andreweick** [comment]
@regisphilibert hmm, ok, <thinking-aloud>

I think putting everything in a "theme" directory will get at what I want -- at some point I expect I'll want a new theme and want an upgrade path :-)

I *really* like what @budparr [said](https://github.com/theNewDynamic/mfocus-tracking/issues/5#issuecomment-655806052) the other day -- this was written a few years ago so there are modern tools / techniques to use.  So while I don't want to throw out the baby with the bath water I also don't want to break (your) back keeping the theme moving forward -- 

So in your opinion, is it better to start "clean" with new thinking / tool / strategies and develop, or retro fit the existing theme with (those new tools / techniques / etc)?

</thinking-aloud>

**Comment by regisphilibert** [comment]
Hi @andreweick I think the best would be in a foreseeable future to port this theme to our modern ways of doing. But it's out of the scope of this current sprint. I suggest we merge this branch (when ready) and, if we go into another sprint, then take some time to make that theme 2020. 

Thanks.

**Comment by andreweick** [comment]
@regisphilibert seems likes "Tags" is broken?  https://deploy-preview-50--www-eick-com.netlify.app/tags/ comes up 'blank' on current safari and need to scroll to the next screen to see the content?

**Comment by regisphilibert** [comment]
@andreweick I fixed the tags page by applying the same layout of other pages.

**Pull request merged**
